  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Server.SendEmail;
import Services.Answer;
import Services.QandAns;
import Services.user;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Get Correct Answer 
 * @author User
 */
public class Ansers extends javax.swing.JFrame {

    static String userName;

    public Ansers() {
        initComponents();
        getDetails();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonSendMail1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totmarks = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_close_window_50px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 60, 60));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("<html><body>Click To Recive your result<br> via Email:</body></html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jButtonSendMail1.setBackground(new java.awt.Color(0, 51, 153));
        jButtonSendMail1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButtonSendMail1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSendMail1.setText("SEND ME MAIL");
        jButtonSendMail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMail1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSendMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 150, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/mail.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 320, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/logo2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/answersback.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 580, 430));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Results");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 120, 40));

        totmarks.setBackground(new java.awt.Color(204, 204, 204));
        totmarks.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        totmarks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(totmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 750, 110, 30));

        result.setBorder(null);
        result.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(result);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 590, 630));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("Total Marks:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 750, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/result.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 460, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
       int pop = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", pop);
        if (result == 0) {
            Login frame = new Login();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonSendMail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMail1ActionPerformed
        try {
            /***
             * send the response output into the email server.
             */
            
            SendEmail.sendMail(Login.userName, result.getText(), "Quiz Dashboard");
            JOptionPane.showMessageDialog(this, "Email send Succesfully.");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSendMail1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ansers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ansers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ansers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ansers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ansers().setVisible(true);
            }
        });
    }

    /**
     * *
     * To get the solved output from server side.
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonSendMail1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane result;
    private javax.swing.JLabel totmarks;
    // End of variables declaration//GEN-END:variables

    private void getDetails() {
        Registry reg;
        try {
            String res = null;
            ArrayList<QandAns> response = new ArrayList<>();
            response = new RMIConnection().getServer().getDetails(Login.userName123);
            /***
             * Get user name from cookie 
             * from local disk file 
             */
            FileInputStream fileInput = null;
            ObjectInputStream objInput = null;
            fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\userCookie.iq"));
            objInput = new ObjectInputStream(fileInput);
            user u1 = null;
            u1 = (user) objInput.readObject();
            /***
             * Get user total marks 
             */
            String Tot = null;
            Tot = new RMIConnection().getServer().getUmarks(u1.getEmail());
            if (Tot.isEmpty() || Tot.equals(null)) {
                totmarks.setText("you have no marks");
            } else {
                totmarks.setText(Tot);
            }
            
            fileInput = null;
            objInput = null;
            
            /***
             * get All answers save to the temporary values from local disk
             */
            for (int x = 1; x <= 10; x++) {
                try {
                    try {
                        fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\ans" + x + ".iq"));
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /***
                     * if question answer is false fetch the correct answer 
                     */
                    objInput = new ObjectInputStream(fileInput);
                    Answer finAns = (Answer) objInput.readObject();
                    if (!finAns.getProAnswer().equals("True")) {
                        res = res + "Question Number: " + x + "\n" + response.get(x - 1).getQuestion() + "\n Answer: " + response.get(x - 1).getAnswer() + "\n\n";
                    }
                } catch (IOException ex) {
                    Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        objInput.close();
                    } catch (IOException ex) {
                        Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (res.isEmpty() || res.equals(null)) {
                result.setText("Congratulations !!!\n You have successfully answers to the questions.....");
            } else {
                result.setText(res);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
