/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Services.Answer;
import Services.answerServiceLayer;
import Services.user;
import javax.swing.Timer;
import java.awt.event.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class games9 extends javax.swing.JFrame {

    /**
     * Creates new form games9
     */
    
   int i =21;
   Timer T;

    /**
     *
     */
    public games9() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.T = new Timer (1000, (ActionEvent e) -> {
            i--;
            
            if (i>=0)
                jLabel5.setText("TimeLeft:"+i);
            
                if (i == 0 ) {
                try {
                    /***
                     * save answer after the overdue
                     */
                    Answer ans2 = new Answer(10, "Over Due");
                    answerServiceLayer anssv2 = new answerServiceLayer();
                    anssv2.saveProAnswer(10, ans2);
                    
                    /***
                     * send values to other side before the overdue 
                     * Read saved answers temporary saved in localdisk
                     */
                    Answer [] ansArray = new Answer[10];
                    FileInputStream fileInput = null;
                    ObjectInputStream objInput = null;
                    /***
                     * read local temp value file by file and make a array list
                     */
                    for (int x=1; x<=10; x++ ) {
                        try {
                            try {
                                fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\ans"+x+".iq"));
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            objInput = new ObjectInputStream(fileInput);
                            Answer finAns = (Answer) objInput.readObject();
                            ansArray [x-1] = finAns;
                        } catch (IOException ex) {
                            Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                            try {
                                objInput.close();
                            } catch (IOException ex) {
                                Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    
                    /***
                     * read values from user cookie
                     */
                    fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\userCookie.iq"));
                    objInput = new ObjectInputStream(fileInput);
                    user u1 = null;
                    u1 = (user) objInput.readObject();
                    
                    
                    /***
                     * send read values server side
                     */
                    new RMIConnection().getServer().saveAnswers(ansArray, u1.getEmail());
                    
                    new Ansers().setVisible(true);
                    T.stop();
                    dispose();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAnswerProvided = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 244, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("COUNTDOWN:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 170, 110));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setText("Fill in the question mark?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 50));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/q9.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_puzzled_70px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, 70));

        txtAnswerProvided.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAnswerProvided.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(txtAnswerProvided, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 160, 50));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel8.setText("Answer:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/quiz back2.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 650));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 970, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/logo1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 278, 96));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/quit.png"))); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 12, 130, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/gameback.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 225, 140, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/gameback2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, -1, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
             // TODO add your handling code here:
             String answer;
             Answer ans1;
             answer = txtAnswerProvided.getText();
             
             if (!(answer.isEmpty() || answer.equals(null))) {
                 if (answer.equals("25")) {
                     ans1  = new Answer(10, "True");
                 } else {
                     ans1 = new Answer(10, "False");
                 }
             } else {
                 ans1 = new Answer(10, "Skipped");
             }
             
             /***
              * create object array for get saved temporary values to save in object array
              */
             
             answerServiceLayer ansSv = new answerServiceLayer();
             ansSv.saveProAnswer(10, ans1);
             
             Answer [] ansArray = new Answer[10];
             FileInputStream fileInput = null;
             ObjectInputStream objInput = null;
             for (int x=1; x<=10; x++ ) {
                 try {
                     try {
                         fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\ans"+x+".iq"));
                     } catch (FileNotFoundException ex) {
                         Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     objInput = new ObjectInputStream(fileInput);
                     Answer finAns = (Answer) objInput.readObject();
                     ansArray [x-1] = finAns;
                 } catch (IOException ex) {
                     Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                 } finally {
                     try {
                         objInput.close();
                     } catch (IOException ex) {
                         Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 }
             }
             
             /***
              * read values from user cookie 
              */
             fileInput = new FileInputStream(new File("D:\\iqQuizProTemp\\userCookie.iq"));
             objInput = new ObjectInputStream(fileInput);
             user u1 = null;
             u1 = (user) objInput.readObject();
             
             new RMIConnection().getServer().saveAnswers(ansArray, u1.getEmail());
            
            //System.exit(0);
            new Ansers().setVisible(true);
              T.stop();
              dispose();
              
             
            
         } catch (FileNotFoundException ex) {
             Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(games9.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        T.stop();
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        T.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(games9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(games9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(games9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(games9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new games9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAnswerProvided;
    // End of variables declaration//GEN-END:variables
}
