/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author User
 */

import Services.Answer;
import Services.answerServiceLayer;
import javax.swing.Timer;
import java.awt.event.*;

/**
 *
 * @author User
 */
public class games8 extends javax.swing.JFrame {

   int i =21;
   Timer T;

    /**
     *give variable name Timer as a T
     * give each question time limit
     * if time is overdue go to next question
     */
    public games8() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.T = new Timer (1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                i--;
                
                if (i>=0)
                    jLabel5.setText("TimeLeft:"+i);
                
                if (i == 0 ) {
                    Answer ans2 = new Answer(9, "Over Due");
                    answerServiceLayer anssv2 = new answerServiceLayer();
                    anssv2.saveProAnswer(9, ans2);
                    new games9().setVisible(true);
                    T.stop();
                    dispose();
                }
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAnswerProvided = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/logo1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 278, 96));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/quit.png"))); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 12, 130, 70));

        jPanel2.setBackground(new java.awt.Color(247, 244, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("COUNTDOWN:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 170, 110));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setText("Replace the question mark in the above problem with the appropriate number?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 50));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/q8.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 290, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_puzzled_70px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 70));

        txtAnswerProvided.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAnswerProvided.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtAnswerProvided.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnswerProvidedFocusGained(evt);
            }
        });
        txtAnswerProvided.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerProvidedActionPerformed(evt);
            }
        });
        txtAnswerProvided.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnswerProvidedKeyPressed(evt);
            }
        });
        jPanel2.add(txtAnswerProvided, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 160, 50));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel8.setText("Answer:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/quiz back2.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 650));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 115, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/gameback.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 225, 130, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/gameback2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 239, -1, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        T.stop();
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String answer;
        Answer ans1;
        answer = txtAnswerProvided.getText();

        if (!(answer.isEmpty() || answer.equals(null))) {
            if (answer.equals("6")) {
                ans1  = new Answer(9, "True");
            } else {
                ans1 = new Answer(9, "False");
            }
        } else {
            ans1 = new Answer(9, "Skipped");
        }

        answerServiceLayer ansSv = new answerServiceLayer();
        ansSv.saveProAnswer(9, ans1);
        new games9().setVisible(true);
        T.stop();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAnswerProvidedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerProvidedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerProvidedActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    T.start();
    }//GEN-LAST:event_formWindowOpened

    private void txtAnswerProvidedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerProvidedKeyPressed
         /***
         * event action to when press enter key to submit answer and go next question
         */
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
         String answer;
        Answer ans1;
        answer = txtAnswerProvided.getText();

        if (!(answer.isEmpty() || answer.equals(null))) {
            if (answer.equals("6")) {
                ans1  = new Answer(9, "True");
            } else {
                ans1 = new Answer(9, "False");
            }
        } else {
            ans1 = new Answer(9, "Skipped");
        }

        answerServiceLayer ansSv = new answerServiceLayer();
        ansSv.saveProAnswer(9, ans1);
        new games9().setVisible(true);
        T.stop();
        dispose();
        }
    }//GEN-LAST:event_txtAnswerProvidedKeyPressed

    private void txtAnswerProvidedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnswerProvidedFocusGained
        txtAnswerProvided.setText("");
        
    }//GEN-LAST:event_txtAnswerProvidedFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(games8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(games8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(games8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(games8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new games8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAnswerProvided;
    // End of variables declaration//GEN-END:variables
}
